version: '3'

services:
    myweb:
        image: node:11
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        working_dir: /usr/src/app
        env_file:
            - ./Docker/web.env
        ports:
            - 3000:3000
        depends_on:
            - mydb
            - mytestdb
        command: npm run dev  


    mydb:
        image: postgres:11
        volumes:
            - postgres_data_dev:/var/lib/postgresql/data
        env_file:
            - ./Docker/db.env

    mytestdb:
        image: postgres:11
        volumes:
            - postgres_data_test:/var/lib/postgresql/data
        env_file:
            - ./Docker/testdb.env
                    
volumes:
    postgres_data_dev:
    postgres_data_test:    